name: bom_base_ui
description: BOM-Base client UI

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  material_floating_search_bar: ^0.3.4
  dio: ^4.0.0
  provider: ^5.0.0
  intl: ^0.17.0
  yeet: ^0.4.0
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.16.8
  mockito: ^5.0.9
  build_runner: ^2.0.4
  # https://stackoverflow.com/questions/67700083/error-on-flutter-pub-run-build-runner-build/67702879#67702879
  analyzer: 1.5.0 # Versions beyond 1.5.0 currently break build_runner

flutter:
  uses-material-design: true
